# Generated by Django 3.0.4 on 2020-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorized',
            name='authorized',
            field=models.BooleanField(default=True),
        ),
    ]
