# Generated by Django 3.0.4 on 2020-03-31 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_remove_authorized_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorized',
            name='last_visited',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
